DATA_PATH='./data/data.tsv'
GLOVE_DIR_PATH='./glove.twitter.27B'
CHECKPOINT_FILE_PATH='./models/weights.best.hdf5'

MAX_SENT_LENGTH=100
MAX_SENTS=15
MAX_NB_WORDS=20000
EMBEDDING_DIM=100
VALIDATION_SPLIT=0.2
NUM_EPOCHS=12
BATCH_SIZE=64
